# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                location: '%kernel.cache_dir%/flysystem'
        archive_adapter:
            local:
                location: '%kernel.project_dir%/var/archive'
        settings_adapter:
            local:
                location: '%kernel.project_dir%/var/settings'
        backup_adapter:
            local:
                location: '%kernel.project_dir%/var/backup'

        # Dropbox adapters to store everything remotely, to free space and reduce data storage needed
        default_adapter_dpbx:
            custom:
                service: dropbox_config
        archive_adapter_dpbx:
            custom:
                service: dropbox_archive
        settings_adapter_dpbx:
            custom:
                service: dropbox_settings
        backup_adapter_dpbx:
            custom:
                service: dropbox_backup

    filesystems:
        backup_filesystem:
            adapter: backup_adapter #_dpbx
        settings_filesystem:
            adapter: settings_adapter #_dpbx
        archive_filesystem:
            adapter: archive_adapter #_dpbx
        default_filesystem:
            adapter: default_adapter #_dpbx
