---
all:
  hosts:
    local:
      ansible_connection: local
    vb:
#      ansible_ssh_host: "{{ host_ssh_ip }}"
      ansible_ssh_host: 192.168.56.5
      ansible_user: vagrant
    gcp:
      ## todo don't know how make it secret, am using private hosts for gcp as vb :(
      ansible_ssh_host: "{{ host_ssh_ip }}"
      ansible_user: "{{ host_user_name }}"
