---
- name: Install locales package
  become: true
  apt:
    name: locales
  tags:
    -system

- name: Ensure localisation files for '{{ config_system_locale }}' are available
  become: true
  locale_gen:
    name: "{{ config_system_locale }}"
    state: present
  tags:
    - system

- name: Ensure localisation files for '{{ config_system_language }}' are available
  become: true
  locale_gen:
    name: "{{ config_system_language }}"
    state: present
  tags:
    - system

- name: Get current locale and language configuration
  command: localectl status
  register: locale_status
  changed_when: false
  tags:
    - system

- name: Parse 'LANG' from current locale and language configuration
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"
  tags:
    - system


- name: Parse 'LANGUAGE' from current locale and language configuration
  set_fact:
    locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"
  tags:
    - system

- name: Configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
  become: true
  command: localectl set-locale LANG={{ config_system_locale }} LANGUAGE={{ config_system_language }}
  changed_when: locale_lang != config_system_locale or locale_language != config_system_language
  tags:
    - system